Class7/config/routes.rb
Rails.application.routes.draw do
  

  root 'sessions#new'

  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create", as: :login
  get "/log-out" => "sessions#destroy", as: :logout

  resources :users do
    resources :posts
  end

end

Class7/app/models/post.rb
class Post < ActiveRecord::Base

belongs_to :user
end

Class7/app/models/user.rb
class User < ActiveRecord::Base
	
	attr_accessor :password

	validates_confirmation_of :password
	before_save :encrypt_password
	has_many :posts

	def encrypt_password
	self.password_salt = BCrypt::Engine.generate_salt
	self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)	
	end

	def self.authenticate(email, password)
		user = User.where(email: email).first
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
		user
		else
		nil
		end
	end

end

Class7/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  			
  def current_user
       @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

Class7/app/controllers/home_controller.rb
class HomeController < ApplicationController
  
	def index
  	end

end

Class7/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  

  			def index
  				@posts = Post.all
  				@user = User.find(params[:user_id])
  			end

  			def show
  				@post = Post.find(params[:id])
  			end

  			def new
  				@post = Post.new
  				@user = User.where(params[:user_id]).first
  			end

  			def create
  				@post = Post.new(post_params)
			if @post.save
			flash[:notice] = "Post was created"
			else
			flash[:alert] = "Post wasn't created"
			end
			redirect_to user_posts_path 
  			end

  			def destroy
  			@post = Post.find(params[:id])   
             @user = User.where(params[:user_id]).first
             if @post.destroy     
              flash[:notice] = "Post has been removed "   
            else     
              flash[:alert] = "Sorry but this post can't be deleted"   
            end   
              redirect_to user_posts_path
  			end

        def edit
          @posts = Post.find(params[:id])
          @user = User.where(params[:user_id]).first
         end
         
  			def update
  			 @post = Post.find(params[:id])
           		if @post.update(post_params)
          		flash[:notice] = "Post has been renamed"
          	else
          	flash[:alert] = "We're sorry something went wrong"
            end
          	redirect_to user_posts_path
  			end


  private
		
		def post_params
		params.require(:post).permit(:title, :description)
		end
end

Class7/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  		def new
  
  		end

  		def create
  
		@user = User.authenticate(params[:email], params[:password])

			if @user
			flash[:notice] = "You've been logged in."
			session[:user_id] = @user.id
			redirect_to user_path @user

			else
			flash[:alert] = "There was a problem logging you in."
			redirect_to log_in_path
			end

 		 end

  		def destroy
  
  			session[:user_id] = nil
			flash[:notice] = "You've been logged out successfully."
			redirect_to "/"

  			end

end

Class7/app/controllers/users_controller.rb
class UsersController < ApplicationController
  	
  	def new
  		@user = User.new
  	end

  	def create
  		@user = User.new(user_params)
			if @user.save
			flash[:notice] = "Welcome to the site!"
			session[:user_id] = @user.id
			redirect_to user_path @user
			else
			flash[:alert] = "There was a problem creating your account. Please try again."
			redirect_to new_user_path
			end

  	end

  	def show
  	@user = User.find(params[:id])
  	end

  	private
	
	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation)
	end
end

Class7/app/helpers/application_helper.rb
module ApplicationHelper
end

Class7/app/helpers/home_helper.rb
module HomeHelper
end

Class7/app/helpers/posts_helper.rb
module PostsHelper
end

Class7/app/helpers/sessions_helper.rb
module SessionsHelper
end

Class7/app/helpers/user_helper.rb
module UserHelper
end

Class7/app/views/home/index.html.erb
<h1>Welcome to the homepage</h1>

<%= link_to "logout", logout_path %>

Class7/app/views/posts/edit.html.erb
<h1>You can edit your post here</h1>
<br>
<%= form_for [@user,@posts] do |f| %>   
<%=f.label :title %>   
<%=f.text_field :title %>
<%=f.label :description %>   
<%=f.text_field :description %>
<%=f.submit :update %> 
<% end %>
<br>
<p><center>Otherwise you can <%= link_to "Go back", :back%><center></p>

Class7/app/views/posts/index.html.erb
<br>
<h1> <center><u>Posts page</u></center></h1>
<br>

<% @posts.each do |post| %>
<p> <u> <%= post.title %></u> <%= post.user_id %> <%= link_to "Post description", user_post_path(params[:user_id],post.id) %>
	<%= link_to 'Edit this post', edit_user_post_path(params[:user_id],post.id) %>
 <%= link_to 'Delete this post', user_post_path(params[:user_id],post.id), method: :delete %>
</p>

<% end %>

<center><%= link_to "Go home", user_path(@user)%> </center>

Class7/app/views/posts/new.html.erb
<h1> Create a new Post </h1>
<br>
<%= form_for [@user,@post] do |f| %>   
<%=f.label :title %>   
<%=f.text_field :title %>
<%=f.label :description %>   
<%=f.text_field :description %>
<%=f.submit %> 
<% end %>

<br>
<center><%= link_to "Go home", :back %><center>

Class7/app/views/posts/show.html.erb
<h1><center>Post details</center></h1>
<br>
<p><%= @post.title %> <%= @post.description %></p>
<%= link_to "Go back", :back %>
<br>