secondapp/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :posts

  root 'users#index'

end

secondapp/app/models/post.rb
class Post < ActiveRecord::Base
end

secondapp/app/models/user.rb
class User < ActiveRecord::Base
end

secondapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

secondapp/app/controllers/posts_controller.rb
class PostsController < ApplicationController

layout 'layout1'

		def index
		@posts = Post.all
		end

		def show
		@post = Post.find(params[:id])
		end

end

secondapp/app/controllers/users_controller.rb
class UsersController < ApplicationController

layout 'layout2'
		
		def index
			@users = User.all
		
	if @users.present?    
	flash[:notice] = "Users display successfully."   
	else
    flash[:alert] = "Sorry, there were no users to display."
  	end
	
		end

		def show
		@user = User.find(params[:id])
		end 
end

secondapp/app/helpers/application_helper.rb
module ApplicationHelper
end

secondapp/app/views/posts/_menu2.html.erb
<h1> For Your Information</h1>

<%= other_message %>

secondapp/app/views/posts/index.html.erb
<h1> <center> Welcome to our Post page</center></h1>

<%= render 'menu2', other_message: 'You must remove /posts to the current browser to go back to the users page' %>

<% @posts.each do |p| %>
<p> <%= p.title %><%= link_to " Post content", post_path(p) %> </p>
<% end %>

secondapp/app/views/posts/show.html.erb
<h1> Current Post</h1>

<%= @post.title %>
<%= @post.body %>

<%= link_to "Go back", post_path() %>

secondapp/app/views/users/_menu.html.erb
<h1> For Your Information</h1>

<%= message %>

secondapp/app/views/users/index.html.erb
<h1><center> Welcome to our User page </center></h1>
<br>
<%= render 'menu', message: 'You must add /posts to the current browser to see the list of posts'%>
<br>
<h2><b>As of now, we have: </b></h2>

<% @users.each do |u| %>
<p> <%= u.name %> <%= link_to "User information", user_path(u)%></p>
<% end %>

secondapp/app/views/users/show.html.erb
<h1> Show me a user </h1>

<%= @user.name %>
<%= @user.email %>

<%= link_to "Home", root_path() %>